# Generated by Django 5.0.6 on 2024-05-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_genre'),
        ('movie', '0004_rating'),
    ]

    operations = [
    ]
